<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>NeuralResonanceEngine.Structures.RedNucleus</AssemblyName>
    <RootNamespace>NeuralResonanceEngine.Structures.RedNucleus</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Protocol\NeuralResonanceEngine.Protocol.csproj" />
    <ProjectReference Include="..\..\Shared.Contracts\NeuralResonanceEngine.Shared.Contracts.csproj" />
  </ItemGroup>
</Project>
