using NeuralResonanceEngine.Shared.Contracts;

namespace NRE.WorldSim;

public sealed record WorldSimulationSnapshot(
    string ProtocolVersion,
    string SessionId,
    int ProcessId,
    bool Running,
    bool WorldReady,
    DateTimeOffset GeneratedUtc,
    DateTimeOffset SessionStartedUtc,
    double ElapsedSeconds,
    long WorldTick,
    string ControlEndpoint,
    bool BrainConnected,
    double TelemetryAgeSeconds,
    double FrameAgeSeconds,
    string BrainStatus,
    int Seed,
    double AvatarX,
    double AvatarY,
    double AvatarZ,
    double AvatarHeadingDeg,
    double AvatarForwardSpeed,
    double AvatarTurnRateDeg,
    double AvatarVerticalVelocity,
    bool AvatarGrounded,
    double DistanceTravelled,
    int VisitedTerrainCells,
    int ExplorableTerrainCells,
    long NeuronalMotorDispatchTotal,
    long NeuronalLocomotorDispatchTotal,
    long NeuronalManipulatorDispatchTotal,
    double LeftMotorDrive,
    double RightMotorDrive,
    double ManipulatorDrive,
    double HeadYawDrive,
    double HeadPitchDrive,
    double StandDrive,
    double CrouchDrive,
    double SitDrive,
    double LieDrive,
    PhysicalArticulationFrame Articulation,
    long InteractionAttempts,
    long InteractionSuccesses,
    long InteractionOutOfReach,
    long InteractionOutsideCone,
    long InteractionOccluded,
    long InteractionUnavailable,
    string LastInteractionOutcome,
    long RetinalFramesAccepted,
    long LeftRetinalFramesAccepted,
    long RightRetinalFramesAccepted,
    long CochlearFramesAccepted,
    long PhysicalBodyFramesAccepted,
    long PhysicalBodyFramesRejected,
    long SomaticFramesAccepted,
    long SomaticFramesRejected,
    long BodyInputFailures,
    string LastBodyInputError,
    int FoodConsumed,
    int WeaponPickupsCollected,
    int WeaponCharges,
    int WaterInteractions,
    int PredatorsActive,
    bool PredatorsSuspended,
    int PredatorsNeutralized,
    double StoredEnergyJoules,
    double TissueIntegrityFraction,
    double HydrationFraction,
    string VitalState,
    double VitalStateSeconds,
    int PhysicalDeaths,
    bool InShelter,
    bool NeuronalSleep,
    int CollisionHits,
    long TickFailures,
    IReadOnlyList<WorldEntityStatus> FoodPickups,
    IReadOnlyList<WorldEntityStatus> WeaponPickups,
    IReadOnlyList<WorldEntityStatus> Predators,
    IReadOnlyList<WorldEntityStatus> Shelters,
    bool MotorTrainingMode = false,
    string TerrainAscentMode = "none",
    double TerrainAscentProgress = 0.0,
    long TerrainAscentEncounters = 0,
    long TerrainAscentStarted = 0,
    long TerrainStepStarted = 0,
    long TerrainMantleStarted = 0,
    long TerrainAscentCompleted = 0,
    long TerrainStepCompleted = 0,
    long TerrainMantleCompleted = 0,
    long TerrainAscentAborted = 0,
    long TerrainAscentRejected = 0,
    string TerrainAscentLastOutcome = "none",
    double LeftHipCoronalDrive = 0.0,
    double RightHipCoronalDrive = 0.0,
    double LeftAnkleSagittalDrive = 0.0,
    double RightAnkleSagittalDrive = 0.0,
    double LeftAnkleCoronalDrive = 0.0,
    double RightAnkleCoronalDrive = 0.0,
    double TrunkYawDrive = 0.0,
    long SomaticFrameRetries = 0,
    long SomaticFrameRetryRecoveries = 0,
    double PhysicalContactTissueDamageFraction = 0.0,
    long PhysicalImpactDamageEvents = 0,
    long SustainedPressureDamageEpisodes = 0,
    string MostDamagedContactRegion = "none",
    string DevelopmentStage = "Terrain",
    double LeftHandGraspDrive = 0.0,
    double RightHandGraspDrive = 0.0,
    string LeftHandPhase = "Open",
    string RightHandPhase = "Open",
    double LeftHandPhaseSeconds = 0.0,
    double RightHandPhaseSeconds = 0.0,
    double LeftHandApertureFraction = 1.0,
    double RightHandApertureFraction = 1.0,
    double LeftGripForceNewtons = 0.0,
    double RightGripForceNewtons = 0.0,
    double LeftHandFatigue = 0.0,
    double RightHandFatigue = 0.0,
    double LeftHandSlip = 0.0,
    double RightHandSlip = 0.0,
    long ReachEntries = 0,
    long HandContacts = 0,
    long Grasps = 0,
    long Holds = 0,
    long Releases = 0,
    long GraspMisses = 0,
    long FatigueReleases = 0,
    double BrainFrameLatencyMilliseconds = 0.0,
    int ConsecutiveSlowBrainFrames = 0,
    long BrainFrameOverloadSafetyPauses = 0,
    string LastBrainFrameOverloadReason = "none");

public sealed record WorldEntityStatus(
    string Kind,
    double X,
    double Y,
    double Z,
    double HeadingDeg,
    string? Variant);
